# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Uma viagem pelo meu jardim • Diego Schild Smiths
author: Diego Schild Smiths
description: Uma viagem pelo meu jardim • Diego Schild Smiths
keywords: diego schild smiths, diego, schild, smiths, pagina, site, pessoal, blog


# Contact
email_address: diegossmiths@gmail.com
gitlab_username: diegossmiths
instagram_username: diegossmiths
lastfm_username: diegossmiths
strava_username: diegossmiths
spotify_username: tekonaza


# Site settings:

url: "https://diegossmiths.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # usado para subdomínios dentro do site
theme-color: '#008b8b'
#theme: minima
languages: pt_BR
lang: pt
locale: tp_BR
permalink: /blog/:title/
markdown: kramdown

# paginate: 10
# paginate_path: /page:num/


# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
