# Arquivo de configuração do sítio
# Versão 1.2
# 2021-07-12
# GPLv3

# SEO > https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Uma viagem pelo meu jardim • Diego Schild Smiths
author: Diego Schild Smiths
description: Uma viagem pelo meu jardim • Diego Schild Smiths
keywords: diego schild smiths, diego, schild, smiths, pagina, site, pessoal, blog


# Contatos
email_address: diegossmiths@fastmail.com
gitlab_username: diegossmiths
instagram_username: diegossmiths
lastfm_username: diegossmiths
strava_username: diegossmiths
pocket_username: diegossmiths


# Configurações:
url: "https://umaviagempelomeujardim.net"
baseurl: "" # usado para subdomínios dentro do site
theme-color: '#008b8b'
languages: pt_BR
lang: pt
locale: pt_BR
permalink: /blog/:title/
markdown: kramdown
#paginate: 10
#paginate_path: /page:num/


# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Excluir do processamento
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

